### ISSUE TITLE
Unable to extract mwsc zip

### ISSUE THREAD

**Issue by paynetechnologies** [bulldog2011/mwsc#1]
Download zip package from repository mentioned in version history below, latest stable release is 0.6.0, then extract the zip file and run mwsc script in command line:

![mwsc error](https://f.cloud.github.com/assets/628590/405556/84ebc718-a9ea-11e2-812d-7ac2ab71789b.jpg)

Thanks

**Comment by bulldog2011** [comment]
Hi,

You must have downloaded the wrong link, please don't download the blob link, instead, you should download the raw link:
https://github.com/bulldog2011/bulldog-repo/raw/master/repo/releases/com/leansoft/mwsc/0.6.0/mwsc-0.6.0-bin.zip

please try again.

Thx!
-William

**Comment by paynetechnologies** [comment]
William,

Thanks ... for the correct link...I downloaded and unzipped...

Next issue was the realization that I need the SDK and not simply java...So
I will download the Java SDK

# 

I:\temp\mwsc-0.6.0\bin>mwsc
JDK's tools.jar was not found in P:\program files\Java\lib\tools.jar.
Usually th
is means you are running JRE, not JDK. Please use the java command in JDK
5.0 or

#  later (not JRE.)

Howard

**Comment by bulldog2011** [comment]
Hi Howard:

Thx for your feedback!

I have updated mwsc to remove JDK dependency, it should work with JRE now, please have a try.

Thx!
-William

**Comment by paynetechnologies** [comment]
William,

I downloaded Java and installed was not able to get rid of the error
message...Google'd it and found a few ideas, ie JAVA_HOME pointing to
install dir of Java and also updating my default path variable....NEITHER
worked...I ended up copy the P:/Progam Files/Java/jdk.1.7.0_021/lib to
P:\program
files\Java\lib and it worked...( I realize that your process is targeting
iOS and Android and I'm running on a Windows XP box...but I will start
development on my Mac once I understand how to put all the pieces
together...) By the way, is there some other email I can contact you?

My plan is to use your processes to create iOS apps targeting Amazon's web
services, i.e,
(#1)
http://webservices.amazon.com/AWSECommerceService/AWSECommerceService.wsdl

There is one Amazon API that does not appear to have a wsdl...(#2)
https://developer.amazonservices.com/ In this case, is there some way to
create a wsdl from the api and then process the generated wsdl via mwsc?

I would like to use one process for both of Amazon's web services...At the
moment, it seems that I could use your processes for (#1) but would have to
use REST for (#2).

What are your thoughts on this?

Anyway, I appreciate your work and will give you feedback as I work my way
through your tutorials.

Thanks in advance,
Howard

**Comment by bulldog2011** [comment]
Hi Howard:

my comments:
1. I just updated the mwsc zip file and verified it locally with JRE, have you downloaded the zip again?
2. my email: 51startup@sina.com
3. I have checked the Java SDK for Amazon marketplace web service, it's based on JAXB, so it's possible to generate xsd from its java source and build a similar custom SDK for iOS or Android, also, amazon provides some xsd(https://images-na.ssl-images-amazon.com/images/G/02/rainier/help/XML_Documentation_Intl._V158772716_.pdf), there is just some effort to build a custom SDK for iOS or Android.

Thx!
-William
----- 原始邮件 -----
发件人：paynetechnologies notifications@github.com
收件人：bulldog2011/mwsc mwsc@noreply.github.com
抄送人：bulldog 51startup@sina.com
主题：Re: [mwsc] Unable to extract mwsc zip (#1)
日期：2013年04月22日 22点36分
