### ISSUE TITLE
Unable to run in terminal for generating iOS classes

### ISSUE THREAD

**Issue by saru2020** [bulldog2011/mwsc#2]
When i run the Following command in the terminal on my MAC:
mwsc -pico -prefix PEVideos_ -d generated htttp://sample?wsdl

It shows the following error:
"-bash: mwsc: command not found"

Can someone help me asap? Thanks!

**Comment by paynetechnologies** [comment]
Sounds like the path to mwsc  is not known to bash...try adding the path to mwsc in your profile ....

**Comment by saru2020** [comment]
Please guide on how to add mwsc path to the profile?

**Comment by bulldog2011** [comment]
Hi,

Try this:
Suppose you extrated the mwsc zip package in a local directory, then in the command line, change your current directory to the exteracted mwsc directory, create a 'generated' folder, then run:

bin/mwsc -pico -prefix PEVideos_ -d generated htttp://sample?wsdl

You wil need to add executable right the the bin/mwsc script first time before you can run it.

Thx!
-William

**Comment by saru2020** [comment]
"You wil need to add executable right the the bin/mwsc script first time before you can run it."
Sorry, i can't really understand, what the above means?. Can you brief it please?

Also, i've tried before itself by changing the directory in command line to the extracted dir, with this command:
"bin/mwsc -pico -prefix PEVideos_ -d generated htttp://sample?wsdl",
but now i get this following error:
"-bash: bin/mwsc: Permission denied".

**Comment by paynetechnologies** [comment]
You must tell the operating system that its ok to run or execute mwsc...you do this by giving 'execute' permissions or rights to the mwsc program.

On unix, use the chmod command .... Check google if you need on how....

Something like: chmod +x path-to-mwsc ... Where path-to-mwsc is the directory path to where you downloaded or installed mwsc

Hope that helps 

Payne H.D.
443-249-2102
Paynehd@gmail.com

**Comment by saru2020** [comment]
Ok. Finally i got it to execute by giving out the exact path of mwsc file such as (not by changing the directory of the terminal to the path of the file):
"/Users/saravananv/Downloads/mwsc-0.6.0/bin/mwsc -pico -prefix PEVideos_ -d generated htttp://sample?wsdl"

Before this, I changed the access of the bin folder by doing this:
"sudo chmod 755 -R /bin/mwsc", but not sure what it did.
After executing the above command, the terminal asked for a password, i gave in & it showed this:
"chmod: -R: No such file or directory
chmod: /bin/mwsc: No such file or directory"

**Comment by bulldog2011** [comment]
Hi Saru:

If you are not familar with Linux or MacOS command line environment, just do the code generation in Windows environment, there is a corresponding mwsc.bat file in the bin folder.

After code generation, copy the generated source to your MacOS environment.

Thx!
-William

**Comment by saru2020** [comment]
Thanks Will.
Am done with this now, am able to generate files in my mac itself.
Just wanting to get in touch with the command line :)
