### ISSUE TITLE
Unable to compile mwsc com.leansoft.mxjc.* classes missing

### ISSUE THREAD

**Issue by firefoxNX** [bulldog2011/mwsc#4]
On running "mvn package" I get several compilation errors because com.leansoft.mxjc.\* classes are missing. Are you planning on making those available?

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] mwsc/src/main/java/com/leansoft/mwsc/model/annotation/SOAPBindingAnnotation.java:[3,31] package com.leansoft.mxjc.model does not exist
[ERROR] mwsc/src/main/java/com/leansoft/mwsc/model/annotation/SOAPBindingAnnotation.java:[11,47] cannot find symbol
symbol: class Annotatable
[ERROR] mwsc/src/main/java/com/leansoft/mwsc/model/annotation/WebServiceAnnotation.java:[3,31] package com.leansoft.mxjc.model does not exist
[ERROR] mwsc/src/main/java/com/leansoft/mwsc/model/annotation/WebServiceAnnotation.java:[13,46] cannot find symbol
symbol: class Annotatable
[ERROR] mwsc/src/main/java/com/leansoft/mwsc/module/AbstractWSClientModule.java:[8,31] package com.leansoft.mxjc.model does not exist
[ERROR] mwsc/src/main/java/com/leansoft/mwsc/module/AbstractWSClientModule.java:[9,32] package com.leansoft.mxjc.module does not exist
[ERROR] mwsc/src/main/java/com/leansoft/mwsc/module/AbstractWSClientModule.java:[10,32] package com.leansoft.mxjc.module does not exist
[ERROR] mwsc/src/main/java/com/leansoft/mwsc/module/WSClientModule.java:[6,31] package com.leansoft.mxjc.model does not exist
[ERROR] mwsc/src/main/java/com/leansoft/mwsc/module/WSClientModule.java:[7,31] package com.leansoft.mxjc.model does not exist
[ERROR] mwsc/src/main/java/com/leansoft/mwsc/module/WSClientModule.java:[8,32] package com.leansoft.mxjc.module does not exist
[ERROR] mwsc/src/main/java/com/leansoft/mwsc/module/AbstractWSClientModule.java:[71,19] cannot find symbol

**Comment by bulldog2011** [comment]
Hi,

The project depends on mxjc jar, it's on my github repository, please add flollowing in the pom then rebuild:
`
    <repositories>
        <repository>
          <id>github.release.repo</id>
          <name>Release Repository</name>
          <url>https://raw.github.com/bulldog2011/bulldog-repo/master/repo/releases/</url>
          <releases>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
          </releases>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
        </repository>
        <repository>
          <id>github.snapshot.repo</id>
          <name>Snapshot Repository</name>
          <url>https://raw.github.com/bulldog2011/bulldog-repo/master/repo/snapshots/</url>
          <releases>
            <enabled>false</enabled>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
          </snapshots>
        </repository>
    </repositories>
`

Or, you may checkout mxjc project and build it locally, then you will have a local copy of mxjc jar in your maven cache.

Thx!
-William

**Comment by firefoxNX** [comment]
Thanks that worked.
