### ISSUE TITLE
Error Generating Pico code: method.parameters?first is undefined

### ISSUE THREAD

**Issue by haitham-reda** [bulldog2011/mwsc#7]
Hello, 
I was unable to generate Pico code using mwsc-0.6.0, hereafter the error dump
SEVERE: Error on line 27, column 5 in jar:file:~/Downloads/mwsc-0.6.0/lib/mwsc-0.6.0.jar!/com/leansoft/mwsc/module/pico/template/client-endpoint-soap-interface.fmt
method.parameters?first is undefined.
It cannot be assigned to param

**Comment by bulldog2011** [comment]
There are issues in your wsdl, have fixed the wsdl and sent it to you in the email.

Thx!
-William
